// // This file contains professional, pre-built template definitions for a mobile repair shop.

// export const templates = [
//   {
//     id: "pro-a4-invoice",
//     name: "Professional A4 Invoice",
//     description:
//       "A modern, full-page A4 invoice with clear sections for branding, billing, and terms.",
//     preview: "https://placehold.co/400x565?text=Professional+A4+Invoice",
//     template: {
//       pageSettings: {
//         mode: "paged",
//         size: "a4",
//         orientation: "portrait",
//         width: 595,
//         height: 842,
//         marginTop: 40,
//         marginRight: 40,
//         marginBottom: 40,
//         marginLeft: 40,
//       },
//       pages: [
//         {
//           id: "page-1",
//           width: 595,
//           height: 842,
//           elements: [
//             // Header
//             {
//               id: "logo",
//               type: "Image",
//               x: 0,
//               y: 0,
//               width: 140,
//               height: 70,
//               src: "https://placehold.co/280x140/EFEFEF/31343C?text=Your+Logo",
//             },
//             {
//               id: "shop-name",
//               type: "Text",
//               x: 315,
//               y: 5,
//               width: 200,
//               height: 20,
//               text: "Mobile Repair Experts",
//               fontSize: 18,
//               fontStyle: "bold",
//               align: "right",
//             },
//             {
//               id: "shop-addr",
//               type: "Text",
//               x: 315,
//               y: 28,
//               width: 200,
//               height: 40,
//               text: "123 Tech Lane, Circuit City\nPhone: 555-123-4567",
//               fontSize: 10,
//               align: "right",
//             },

//             // Bill To & Invoice Details
//             {
//               id: "bill-to-title",
//               type: "Text",
//               x: 0,
//               y: 120,
//               width: 100,
//               height: 15,
//               text: "BILL TO",
//               fontSize: 11,
//               fontStyle: "bold",
//             },
//             {
//               id: "customer-name",
//               type: "Text",
//               x: 0,
//               y: 140,
//               width: 250,
//               height: 18,
//               text: "Customer Name",
//               dataBinding: { property: "text", field: "customer.name" },
//               fontSize: 14,
//               fontStyle: "bold",
//             },
//             {
//               id: "customer-addr",
//               type: "Text",
//               x: 0,
//               y: 160,
//               width: 250,
//               height: 30,
//               text: "Customer Address",
//               dataBinding: { property: "text", field: "customer.address" },
//               fontSize: 10,
//             },
//             {
//               id: "invoice-title",
//               type: "Text",
//               x: 315,
//               y: 120,
//               width: 200,
//               height: 25,
//               text: "INVOICE",
//               fontSize: 26,
//               fontStyle: "bold",
//               align: "right",
//             },
//             {
//               id: "invoice-num-label",
//               type: "Text",
//               x: 315,
//               y: 155,
//               width: 100,
//               height: 15,
//               text: "Invoice #",
//               fontSize: 10,
//               align: "right",
//             },
//             {
//               id: "invoice-num-val",
//               type: "Text",
//               x: 420,
//               y: 155,
//               width: 95,
//               height: 15,
//               dataBinding: { property: "text", field: "invoiceNumber" },
//               fontSize: 10,
//               align: "right",
//             },
//             {
//               id: "invoice-date-label",
//               type: "Text",
//               x: 315,
//               y: 170,
//               width: 100,
//               height: 15,
//               text: "Date",
//               fontSize: 10,
//               align: "right",
//             },
//             {
//               id: "invoice-date-val",
//               type: "Text",
//               x: 420,
//               y: 170,
//               width: 95,
//               height: 15,
//               dataBinding: { property: "text", field: "invoiceDate" },
//               fontSize: 10,
//               align: "right",
//             },

//             // Table
//             {
//               id: "items-table",
//               type: "Table",
//               x: 0,
//               y: 220,
//               width: 515,
//               height: 300,
//               dataBinding: { property: "items", field: "items[]" },
//               columns: [
//                 {
//                   header: "Service / Product Description",
//                   dataKey: "description",
//                 },
//                 { header: "Quantity", dataKey: "qty" },
//                 { header: "Unit Price", dataKey: "unitPrice" },
//                 { header: "Total", dataKey: "total" },
//               ],
//             },

//             // Totals Section
//             {
//               id: "subtotal-label",
//               type: "Text",
//               x: 300,
//               y: 550,
//               width: 100,
//               height: 15,
//               text: "Subtotal",
//               fontSize: 11,
//               align: "right",
//             },
//             {
//               id: "subtotal-val",
//               type: "Text",
//               x: 410,
//               y: 550,
//               width: 105,
//               height: 15,
//               dataBinding: { property: "text", field: "subtotal" },
//               fontSize: 11,
//               align: "right",
//             },
//             {
//               id: "tax-label",
//               type: "Text",
//               x: 300,
//               y: 570,
//               width: 100,
//               height: 15,
//               text: "Tax (10%)",
//               fontSize: 11,
//               align: "right",
//             },
//             {
//               id: "tax-val",
//               type: "Text",
//               x: 410,
//               y: 570,
//               width: 105,
//               height: 15,
//               dataBinding: { property: "text", field: "tax" },
//               fontSize: 11,
//               align: "right",
//             },
//             {
//               id: "total-line",
//               type: "Shape",
//               shape: "line",
//               x: 300,
//               y: 595,
//               width: 215,
//               height: 1,
//               stroke: "#000000",
//               strokeWidth: 1,
//             },
//             {
//               id: "total-label",
//               type: "Text",
//               x: 300,
//               y: 605,
//               width: 100,
//               height: 20,
//               text: "TOTAL",
//               fontSize: 14,
//               fontStyle: "bold",
//               align: "right",
//             },
//             {
//               id: "total-val",
//               type: "Text",
//               x: 410,
//               y: 605,
//               width: 105,
//               height: 20,
//               dataBinding: { property: "text", field: "totalAmount" },
//               fontSize: 14,
//               fontStyle: "bold",
//               align: "right",
//             },

//             // Footer
//             {
//               id: "terms-title",
//               type: "Text",
//               x: 0,
//               y: 680,
//               width: 100,
//               height: 15,
//               text: "Terms & Conditions",
//               fontSize: 10,
//               fontStyle: "bold",
//             },
//             {
//               id: "terms-text",
//               type: "Text",
//               x: 0,
//               y: 695,
//               width: 250,
//               height: 40,
//               text: "Payment is due within 30 days. All repairs are guaranteed for 90 days on parts and labor.",
//               fontSize: 8,
//             },
//             {
//               id: "thanks-msg",
//               type: "Text",
//               x: 0,
//               y: 740,
//               width: 515,
//               height: 20,
//               text: "Thank you for your business!",
//               fontSize: 12,
//               fontStyle: "italic",
//               align: "center",
//             },
//             {
//               id: "powered-by",
//               type: "Text",
//               x: 0,
//               y: 755,
//               width: 515,
//               height: 15,
//               text: "Invoice powered by AavanamKit",
//               fontSize: 8,
//               align: "center",
//               fill: "#888888",
//             },
//           ],
//         },
//       ],
//     },
//   },
//   {
//     id: "modern-a5-invoice",
//     name: "Modern A5 Invoice",
//     description: "A compact, stylish A5 invoice, perfect for smaller jobs.",
//     preview: "https://placehold.co/400x282?text=Modern+A5+Invoice",
//     template: {
//       pageSettings: {
//         mode: "paged",
//         size: "a5",
//         orientation: "portrait",
//         width: 420,
//         height: 595,
//         marginTop: 30,
//         marginRight: 30,
//         marginBottom: 30,
//         marginLeft: 30,
//       },
//       pages: [
//         {
//           id: "page-1",
//           width: 420,
//           height: 595,
//           elements: [
//             // Similar structure to A4 but more compact
//             {
//               id: "logo-a5",
//               type: "Image",
//               x: 0,
//               y: 0,
//               width: 100,
//               height: 50,
//               src: "https://placehold.co/200x100/EFEFEF/31343C?text=Logo",
//             },
//             {
//               id: "invoice-title-a5",
//               type: "Text",
//               x: 200,
//               y: 5,
//               width: 160,
//               height: 25,
//               text: "INVOICE",
//               fontSize: 22,
//               fontStyle: "bold",
//               align: "right",
//             },
//             {
//               id: "bill-to-a5",
//               type: "Text",
//               x: 0,
//               y: 80,
//               width: 200,
//               height: 15,
//               text: "BILL TO: Customer Name",
//               dataBinding: { property: "text", field: "customer.name" },
//             },
//             {
//               id: "items-table-a5",
//               type: "Table",
//               x: 0,
//               y: 120,
//               width: 360,
//               height: 250,
//               dataBinding: { property: "items", field: "items[]" },
//               columns: [
//                 { header: "Description", dataKey: "description" },
//                 { header: "Total", dataKey: "total" },
//               ],
//             },
//             {
//               id: "total-val-a5",
//               type: "Text",
//               x: 200,
//               y: 400,
//               width: 160,
//               height: 20,
//               dataBinding: { property: "text", field: "totalAmount" },
//               fontSize: 16,
//               fontStyle: "bold",
//               align: "right",
//             },
//             {
//               id: "thanks-msg-a5",
//               type: "Text",
//               x: 0,
//               y: 500,
//               width: 360,
//               height: 20,
//               text: "Thank you!",
//               fontSize: 12,
//               align: "center",
//             },
//             {
//               id: "powered-by-a5",
//               type: "Text",
//               x: 0,
//               y: 520,
//               width: 360,
//               height: 15,
//               text: "Powered by AavanamKit",
//               fontSize: 8,
//               align: "center",
//               fill: "#888888",
//             },
//           ],
//         },
//       ],
//     },
//   },
//   {
//     id: "pro-thermal-receipt",
//     name: "Professional Receipt",
//     description:
//       "A clean, continuous-roll receipt for thermal printers with all necessary details.",
//     preview: "https://placehold.co/300x500?text=Professional+Receipt",
//     template: {
//       pageSettings: {
//         mode: "roll",
//         width: 220,
//         height: 600,
//         marginTop: 20,
//         marginRight: 10,
//         marginBottom: 20,
//         marginLeft: 10,
//       },
//       pages: [
//         {
//           id: "page-1",
//           width: 220,
//           height: 600,
//           elements: [
//             {
//               id: "logo-th",
//               type: "Image",
//               x: 60,
//               y: 0,
//               width: 80,
//               height: 40,
//               src: "https://placehold.co/160x80/EFEFEF/31343C?text=Logo",
//             },
//             {
//               id: "shop-name-th",
//               type: "Text",
//               x: 0,
//               y: 50,
//               width: 200,
//               height: 15,
//               text: "Mobile Repair Experts",
//               fontSize: 12,
//               fontStyle: "bold",
//               align: "center",
//             },
//             {
//               id: "shop-addr-th",
//               type: "Text",
//               x: 0,
//               y: 65,
//               width: 200,
//               height: 30,
//               text: "123 Tech Lane, Circuit City\nwww.mobilerepair.experts",
//               fontSize: 9,
//               align: "center",
//             },
//             {
//               id: "receipt-num-th",
//               type: "Text",
//               x: 0,
//               y: 105,
//               width: 200,
//               height: 12,
//               text: "Receipt #: 12345",
//               dataBinding: { property: "text", field: "receiptNumber" },
//               fontSize: 9,
//             },
//             {
//               id: "date-th",
//               type: "Text",
//               x: 0,
//               y: 118,
//               width: 200,
//               height: 12,
//               text: "Date: 08/06/2025",
//               dataBinding: { property: "text", field: "receiptDate" },
//               fontSize: 9,
//             },
//             {
//               id: "line-th-1",
//               type: "Shape",
//               shape: "line",
//               x: 0,
//               y: 135,
//               width: 200,
//               height: 1,
//               stroke: "#000000",
//               strokeWidth: 1,
//             },
//             {
//               id: "items-table-th",
//               type: "Table",
//               x: 0,
//               y: 145,
//               width: 200,
//               height: 100,
//               dataBinding: { property: "items", field: "items[]" },
//               columns: [
//                 { header: "Item", dataKey: "description" },
//                 { header: "Price", dataKey: "price" },
//               ],
//             },
//             // Note: In roll mode, the table's Y position determines where it starts, and it grows downwards.
//             // The total section would need to be placed in a non-overlapping Y position if you wanted it *after* the table.
//             // For simplicity, we assume the host application calculates the total and places it in the data.
//             {
//               id: "thanks-th",
//               type: "Text",
//               x: 0,
//               y: 280,
//               width: 200,
//               height: 15,
//               text: "Thank you for your visit!",
//               fontSize: 10,
//               fontStyle: "bold",
//               align: "center",
//             },
//             {
//               id: "barcode-th",
//               type: "Barcode",
//               x: 25,
//               y: 300,
//               width: 150,
//               height: 40,
//               text: "1234567890",
//             },
//           ],
//         },
//       ],
//     },
//   },
//   {
//     id: "pro-repair-ticket",
//     name: "Job Repair Ticket",
//     description:
//       "A compact ticket with essential customer and device information for tracking repairs.",
//     preview: "https://placehold.co/350x250?text=Repair+Ticket",
//     template: {
//       pageSettings: {
//         mode: "paged",
//         size: "custom",
//         width: 320,
//         height: 250,
//         marginTop: 20,
//         marginRight: 20,
//         marginBottom: 20,
//         marginLeft: 20,
//       },
//       pages: [
//         {
//           id: "page-1",
//           width: 320,
//           height: 250,
//           elements: [
//             {
//               id: "ticket-title",
//               type: "Text",
//               x: 0,
//               y: 0,
//               width: 280,
//               height: 20,
//               text: "JOB REPAIR TICKET",
//               fontSize: 16,
//               fontStyle: "bold",
//               align: "center",
//             },
//             {
//               id: "ticket-shop",
//               type: "Text",
//               x: 0,
//               y: 20,
//               width: 280,
//               height: 15,
//               text: "Mobile Repair Experts",
//               fontSize: 9,
//               align: "center",
//             },
//             {
//               id: "line-tk-1",
//               type: "Shape",
//               shape: "line",
//               x: 0,
//               y: 40,
//               width: 280,
//               height: 1,
//               stroke: "#000000",
//               strokeWidth: 1,
//             },
//             {
//               id: "ticket-num-label",
//               type: "Text",
//               x: 0,
//               y: 50,
//               width: 280,
//               height: 15,
//               text: "REPAIR ID",
//               fontSize: 10,
//               align: "center",
//             },
//             {
//               id: "ticket-num-val",
//               type: "Text",
//               x: 0,
//               y: 65,
//               width: 280,
//               height: 30,
//               text: "T-12345",
//               dataBinding: { property: "text", field: "ticketNumber" },
//               fontSize: 24,
//               fontStyle: "bold",
//               align: "center",
//             },
//             {
//               id: "line-tk-2",
//               type: "Shape",
//               shape: "line",
//               x: 0,
//               y: 100,
//               width: 280,
//               height: 1,
//               stroke: "#cccccc",
//               strokeWidth: 1,
//             },
//             {
//               id: "cust-label",
//               type: "Text",
//               x: 10,
//               y: 110,
//               width: 100,
//               height: 15,
//               text: "Customer:",
//               fontSize: 10,
//               fontStyle: "bold",
//             },
//             {
//               id: "cust-val",
//               type: "Text",
//               x: 120,
//               y: 110,
//               width: 150,
//               height: 15,
//               dataBinding: { property: "text", field: "customer.name" },
//               fontSize: 10,
//             },
//             {
//               id: "device-label",
//               type: "Text",
//               x: 10,
//               y: 130,
//               width: 100,
//               height: 15,
//               text: "Device:",
//               fontSize: 10,
//               fontStyle: "bold",
//             },
//             {
//               id: "device-val",
//               type: "Text",
//               x: 120,
//               y: 130,
//               width: 150,
//               height: 15,
//               dataBinding: { property: "text", field: "deviceModel" },
//               fontSize: 10,
//             },
//             {
//               id: "issue-label",
//               type: "Text",
//               x: 10,
//               y: 150,
//               width: 100,
//               height: 15,
//               text: "Reported Issue:",
//               fontSize: 10,
//               fontStyle: "bold",
//             },
//             {
//               id: "issue-val",
//               type: "Text",
//               x: 120,
//               y: 150,
//               width: 150,
//               height: 40,
//               dataBinding: { property: "text", field: "reportedIssue" },
//               fontSize: 10,
//             },
//             {
//               id: "footer-tk",
//               type: "Text",
//               x: 0,
//               y: 200,
//               width: 280,
//               height: 15,
//               text: "Please present this ticket upon collection.",
//               fontSize: 8,
//               align: "center",
//             },
//           ],
//         },
//       ],
//     },
//   },
// ];

// This file contains professional, pre-built template definitions.
// In a real application, this data would be fetched from an API endpoint.

export const proA5LandscapeInvoice = {
  id: "prs-a5-landscape",
  name: "A5 Landscape Invoice",
  description: "A5 landscape with header, table, footer notes & signatures.",
  preview: "https://placehold.co/595x420?text=A5+Invoice+Landscape",
  template: {
    dataSchema: {
      company: {
        name: "string",
        addressLine1: "string",
        addressLine2: "string",
        telephone1: "string",
        telephone2: "string",
      },
      invoice: {
        number: "string",
        date: "string",
        mode: "string",
        salesman: "string",
      },
      customer: { label: "string", value: "string" },
      items: [
        {
          no: "number",
          code: "string",
          description: "string",
          qty: "number",
          rate: "number",
          discount: "number",
          value: "number",
        },
      ],
      summary: {
        totalItems: "number",
        totalQty: "number",
        netTotal: "number",
      },
      footerNotes: ["string"],
      signatures: {
        preparedBy: "string",
        customer: "string",
        issuedBy: "string",
      },
      printed: {
        on: "string",
        at: "string",
      },
    },
    pageSettings: {
      mode: "paged",
      size: "a5",
      orientation: "landscape",
      width: 595,
      height: 420,
      marginTop: 20,
      marginRight: 20,
      marginBottom: 20,
      marginLeft: 20,
    },
    pages: [
      {
        id: "page-1",
        width: 595,
        height: 420,
        elements: [
          // Header: company info
          {
            id: "hdr-company-name",
            type: "Text",
            x: 20,
            y: 20,
            width: 555,
            height: 24,
            text: "Ishop Master ERP",
            fontSize: 18,
            fontStyle: "bold",
            align: "left",
          },
          {
            id: "hdr-address1",
            type: "Text",
            x: 20,
            y: 44,
            width: 400,
            height: 12,
            text: "NO. 1, First Cross Street",
            fontSize: 9,
            align: "left",
          },
          {
            id: "hdr-address2",
            type: "Text",
            x: 20,
            y: 56,
            width: 400,
            height: 12,
            text: "Colombo 11, Sri Lanka",
            fontSize: 9,
            align: "left",
          },
          {
            id: "hdr-telephone",
            type: "Text",
            x: 20,
            y: 70,
            width: 400,
            height: 12,
            text: "Telephone: 011 0000 000 / 0770 000 000",
            fontSize: 9,
            align: "left",
          },

          // Invoice label
          {
            id: "hdr-invoice-label",
            type: "Text",
            x: 440,
            y: 20,
            width: 135,
            height: 18,
            text: "INVOICE",
            fontSize: 16,
            fontStyle: "bold",
            align: "center",
          },

          // Invoice No: split label + value
          {
            id: "hdr-invoice-no-label",
            type: "Text",
            x: 440,
            y: 38,
            width: 60,
            height: 12,
            text: "Invoice No:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "hdr-invoice-no-value",
            type: "Text",
            x: 505,
            y: 38,
            width: 70,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "invoice.number" },
          },

          // Date: split
          {
            id: "hdr-date-label",
            type: "Text",
            x: 440,
            y: 52,
            width: 30,
            height: 12,
            text: "Date:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "hdr-date-value",
            type: "Text",
            x: 475,
            y: 52,
            width: 100,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "invoice.date" },
          },

          // Mode: split
          {
            id: "hdr-mode-label",
            type: "Text",
            x: 440,
            y: 66,
            width: 35,
            height: 12,
            text: "Mode:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "hdr-mode-value",
            type: "Text",
            x: 480,
            y: 66,
            width: 95,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "invoice.mode" },
          },

          // Salesman: split
          {
            id: "hdr-salesman-label",
            type: "Text",
            x: 440,
            y: 80,
            width: 50,
            height: 12,
            text: "Salesman:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "hdr-salesman-value",
            type: "Text",
            x: 495,
            y: 80,
            width: 80,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "invoice.salesman" },
          },

          // Customer box
          {
            id: "cust-box",
            type: "Shape",
            shape: "rect",
            x: 20,
            y: 100,
            width: 555,
            height: 40,
            stroke: "#000000",
            strokeWidth: 1,
          },
          {
            id: "cust-label",
            type: "Text",
            x: 25,
            y: 104,
            width: 60,
            height: 12,
            text: "Customer:",
            fontSize: 9,
            fontStyle: "bold",
          },
          {
            id: "cust-value",
            type: "Text",
            x: 90,
            y: 104,
            width: 485,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "customer.value" },
          },

          // Table header line
          {
            id: "tbl-header-line",
            type: "Shape",
            shape: "line",
            x: 20,
            y: 142,
            width: 555,
            height: 0,
            stroke: "#000000",
            strokeWidth: 1,
          },

          // Items Table
          {
            id: "items-table",
            type: "Table",
            x: 20,
            y: 146,
            width: 555,
            height: 140,
            dataBinding: { property: "items", field: "items[]" },
            columns: [
              { header: "No", dataKey: "no", width: 30 },
              { header: "Code", dataKey: "code", width: 60 },
              { header: "Description", dataKey: "description", width: 220 },
              { header: "Qty", dataKey: "qty", width: 40, align: "right" },
              { header: "Rate", dataKey: "rate", width: 70, align: "right" },
              {
                header: "Discount",
                dataKey: "discount",
                width: 70,
                align: "right",
              },
              { header: "Value", dataKey: "value", width: 65, align: "right" },
            ],
            headerFontSize: 9,
            rowFontSize: 9,
            headerBackground: "#f0f0f0",
            borderWidth: 0.5,
          },

          // Footer Summary: split into six elements
          {
            id: "footer-items-label",
            type: "Text",
            x: 20,
            y: 296,
            width: 80,
            height: 12,
            text: "No. of Items:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "footer-items-value",
            type: "Text",
            x: 105,
            y: 296,
            width: 40,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "summary.totalItems" },
          },
          {
            id: "footer-qty-label",
            type: "Text",
            x: 160,
            y: 296,
            width: 70,
            height: 12,
            text: "Total Qty:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "footer-qty-value",
            type: "Text",
            x: 235,
            y: 296,
            width: 40,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "summary.totalQty" },
          },
          {
            id: "footer-net-label",
            type: "Text",
            x: 290,
            y: 296,
            width: 70,
            height: 12,
            text: "Net Total:",
            fontSize: 9,
            align: "left",
          },
          {
            id: "footer-net-value",
            type: "Text",
            x: 365,
            y: 296,
            width: 70,
            height: 12,
            text: "",
            fontSize: 9,
            align: "left",
            dataBinding: { property: "text", field: "summary.netTotal" },
          },

          // Footer notes, signatures, printed-on … unchanged
          {
            id: "footer-notes",
            type: "Text",
            x: 20,
            y: 316,
            width: 380,
            height: 40,
            text: "",
            fontSize: 7,
            lineHeight: 1.2,
            dataBinding: { property: "text", field: "footerNotes" },
          },
          {
            id: "sig-line",
            type: "Shape",
            shape: "line",
            x: 20,
            y: 366,
            width: 555,
            height: 0,
            stroke: "#000000",
            strokeWidth: 0.5,
          },
          {
            id: "sig-prepared",
            type: "Text",
            x: 20,
            y: 372,
            width: 180,
            height: 12,
            text: "Prepared By: ____________________",
            fontSize: 8,
          },
          {
            id: "sig-customer",
            type: "Text",
            x: 205,
            y: 372,
            width: 190,
            height: 12,
            text: "Customer: _______________________",
            fontSize: 8,
          },
          {
            id: "sig-issued",
            type: "Text",
            x: 420,
            y: 372,
            width: 155,
            height: 12,
            text: "Issued By: ______________________",
            fontSize: 8,
          },
          {
            id: "printed-on",
            type: "Text",
            x: 20,
            y: 390,
            width: 555,
            height: 10,
            text: "",
            fontSize: 7,
            align: "right",
            dataBinding: { property: "text", field: "printed" },
          },
        ],
      },
    ],
  },
};

export const templates = [
  proA5LandscapeInvoice,
  {
    id: "pro-a4-invoice",
    name: "Professional A4 Invoice",
    description:
      "A modern, full-page A4 invoice with clear sections for branding, billing, and terms.",
    preview: "https://placehold.co/400x565?text=Professional+A4+Invoice",
    template: {
      dataSchema: {
        customer: { name: "string", address: "string" },
        invoiceNumber: "string",
        invoiceDate: "string",
        subtotal: "number",
        tax: "number",
        totalAmount: "number",
        items: [
          {
            description: "string",
            qty: "number",
            unitPrice: "number",
            total: "number",
          },
        ],
      },
      pageSettings: {
        mode: "paged",
        size: "a4",
        orientation: "portrait",
        width: 595,
        height: 842,
        marginTop: 40,
        marginRight: 40,
        marginBottom: 40,
        marginLeft: 40,
      },
      pages: [
        {
          id: "page-1",
          width: 595,
          height: 842,
          elements: (function () {
            const ps = {
              width: 595,
              height: 842,
              marginTop: 40,
              marginLeft: 40,
              marginRight: 40,
            };
            const cw = ps.width - ps.marginLeft - ps.marginRight; // 515
            const marginTop = ps.marginTop;
            const left = ps.marginLeft;
            return [
              {
                id: "logo",
                type: "Image",
                x: left + 0,
                y: marginTop + 0,
                width: Math.min(140, cw),
                height: 70,
                src: "https://placehold.co/280x140/EFEFEF/31343C?text=Your+Logo",
              },
              {
                id: "shop-name",
                type: "Text",
                x: left + 315,
                y: marginTop + 5,
                width: Math.min(200, cw - 315),
                height: 20,
                text: "Mobile Repair Experts",
                fontSize: 18,
                fontStyle: "bold",
                align: "right",
              },
              {
                id: "shop-addr",
                type: "Text",
                x: left + 315,
                y: marginTop + 28,
                width: Math.min(200, cw - 315),
                height: 40,
                text: "123 Tech Lane, Circuit City\nPhone: 555-123-4567",
                fontSize: 10,
                align: "right",
              },
              {
                id: "bill-to-title",
                type: "Text",
                x: left + 0,
                y: marginTop + 120,
                width: Math.min(100, cw),
                height: 15,
                text: "BILL TO",
                fontSize: 11,
                fontStyle: "bold",
              },
              {
                id: "customer-name",
                type: "Text",
                x: left + 0,
                y: marginTop + 140,
                width: Math.min(250, cw),
                height: 18,
                text: "Customer Name",
                fontSize: 14,
                fontStyle: "bold",
                dataBinding: { property: "text", field: "customer.name" },
              },
              {
                id: "customer-addr",
                type: "Text",
                x: left + 0,
                y: marginTop + 160,
                width: Math.min(250, cw),
                height: 30,
                text: "Customer Address",
                fontSize: 10,
                dataBinding: { property: "text", field: "customer.address" },
              },
              {
                id: "invoice-title",
                type: "Text",
                x: left + 315,
                y: marginTop + 120,
                width: Math.min(200, cw - 315),
                height: 25,
                text: "INVOICE",
                fontSize: 26,
                fontStyle: "bold",
                align: "right",
              },
              {
                id: "invoice-num-label",
                type: "Text",
                x: left + 315,
                y: marginTop + 155,
                width: Math.min(100, cw - 315),
                height: 15,
                text: "Invoice #",
                fontSize: 10,
                align: "right",
              },
              {
                id: "invoice-num-val",
                type: "Text",
                x: left + 420,
                y: marginTop + 155,
                width: Math.min(95, cw - 420),
                height: 15,
                dataBinding: { property: "text", field: "invoiceNumber" },
                fontSize: 10,
                align: "right",
              },
              {
                id: "invoice-date-label",
                type: "Text",
                x: left + 315,
                y: marginTop + 170,
                width: Math.min(100, cw - 315),
                height: 15,
                text: "Date",
                fontSize: 10,
                align: "right",
              },
              {
                id: "invoice-date-val",
                type: "Text",
                x: left + 420,
                y: marginTop + 170,
                width: Math.min(95, cw - 420),
                height: 15,
                dataBinding: { property: "text", field: "invoiceDate" },
                fontSize: 10,
                align: "right",
              },
              {
                id: "items-table",
                type: "Table",
                x: left + 0,
                y: marginTop + 220,
                width: Math.min(515, cw),
                height: 300,
                dataBinding: { property: "items", field: "items[]" },
                columns: [
                  {
                    header: "Service / Product Description",
                    dataKey: "description",
                    width: 200,
                  },
                  { header: "Qty", dataKey: "qty", width: 50 },
                  { header: "Unit Price", dataKey: "unitPrice", width: 100 },
                  { header: "Total", dataKey: "total", width: 150 },
                ],
              },
              {
                id: "subtotal-label",
                type: "Text",
                x: left + 300,
                y: marginTop + 550,
                width: Math.min(100, cw - 300),
                height: 15,
                text: "Subtotal",
                fontSize: 11,
                align: "right",
              },
              {
                id: "subtotal-val",
                type: "Text",
                x: left + 410,
                y: marginTop + 550,
                width: Math.min(105, cw - 410),
                height: 15,
                dataBinding: { property: "text", field: "subtotal" },
                fontSize: 11,
                align: "right",
              },
              {
                id: "tax-label",
                type: "Text",
                x: left + 300,
                y: marginTop + 570,
                width: Math.min(100, cw - 300),
                height: 15,
                text: "Tax (10%)",
                fontSize: 11,
                align: "right",
              },
              {
                id: "tax-val",
                type: "Text",
                x: left + 410,
                y: marginTop + 570,
                width: Math.min(105, cw - 410),
                height: 15,
                dataBinding: { property: "text", field: "tax" },
                fontSize: 11,
                align: "right",
              },
              {
                id: "total-line",
                type: "Shape",
                shape: "line",
                x: left + 300,
                y: marginTop + 595,
                width: Math.min(215, cw - 300),
                height: 1,
                stroke: "#000000",
                strokeWidth: 1,
              },
              {
                id: "total-label",
                type: "Text",
                x: left + 300,
                y: marginTop + 605,
                width: Math.min(100, cw - 300),
                height: 20,
                text: "TOTAL",
                fontSize: 14,
                fontStyle: "bold",
                align: "right",
              },
              {
                id: "total-val",
                type: "Text",
                x: left + 410,
                y: marginTop + 605,
                width: Math.min(105, cw - 410),
                height: 20,
                dataBinding: { property: "text", field: "totalAmount" },
                fontSize: 14,
                fontStyle: "bold",
                align: "right",
              },
              {
                id: "terms-title",
                type: "Text",
                x: left + 0,
                y: marginTop + 680,
                width: Math.min(100, cw),
                height: 15,
                text: "Terms & Conditions",
                fontSize: 10,
                fontStyle: "bold",
              },
              {
                id: "terms-text",
                type: "Text",
                x: left + 0,
                y: marginTop + 695,
                width: Math.min(250, cw),
                height: 40,
                text: "Payment is due within 30 days. All repairs are guaranteed for 90 days on parts and labor.",
                fontSize: 8,
              },
              {
                id: "thanks-msg",
                type: "Text",
                x: left + 0,
                y: marginTop + 740,
                width: Math.min(515, cw),
                height: 20,
                text: "Thank you for your business!",
                fontSize: 12,
                fontStyle: "italic",
                align: "center",
              },
              {
                id: "powered-by",
                type: "Text",
                x: left + 0,
                y: marginTop + 755,
                width: Math.min(515, cw),
                height: 15,
                text: "Invoice powered by AavanamKit",
                fontSize: 8,
                align: "center",
                fill: "#888888",
              },
            ];
          })(),
        },
      ],
    },
  },
  {
    id: "modern-a5-invoice",
    name: "Modern A5 Invoice",
    description: "A compact, stylish A5 invoice, perfect for smaller jobs.",
    preview: "https://placehold.co/400x282?text=Modern+A5+Invoice",
    template: {
      dataSchema: {
        customer: { name: "string" },
        totalAmount: "number",
        items: [{ description: "string", total: "number" }],
      },
      pageSettings: {
        mode: "paged",
        size: "a5",
        orientation: "portrait",
        width: 420,
        height: 595,
        marginTop: 30,
        marginRight: 30,
        marginBottom: 30,
        marginLeft: 30,
      },
      pages: [
        {
          id: "page-1",
          width: 420,
          height: 595,
          elements: [
            {
              id: "logo-a5",
              type: "Image",
              x: 0,
              y: 0,
              width: 100,
              height: 50,
              src: "https://placehold.co/200x100/EFEFEF/31343C?text=Logo",
            },
            {
              id: "invoice-title-a5",
              type: "Text",
              x: 200,
              y: 5,
              width: 160,
              height: 25,
              text: "INVOICE",
              fontSize: 22,
              fontStyle: "bold",
              align: "right",
            },
            {
              id: "bill-to-a5",
              type: "Text",
              x: 0,
              y: 80,
              width: 200,
              height: 15,
              text: "BILL TO: Customer Name",
              dataBinding: { property: "text", field: "customer.name" },
            },
            {
              id: "items-table-a5",
              type: "Table",
              x: 0,
              y: 120,
              width: 360,
              height: 250,
              dataBinding: { property: "items", field: "items[]" },
              columns: [
                { header: "Description", dataKey: "description", width: 200 },
                { header: "Total", dataKey: "total", width: 200 },
              ],
            },
            {
              id: "total-val-a5",
              type: "Text",
              x: 200,
              y: 400,
              width: 160,
              height: 20,
              dataBinding: { property: "text", field: "totalAmount" },
              fontSize: 16,
              fontStyle: "bold",
              align: "right",
            },
            {
              id: "thanks-msg-a5",
              type: "Text",
              x: 0,
              y: 500,
              width: 360,
              height: 20,
              text: "Thank you!",
              fontSize: 12,
              align: "center",
            },
            {
              id: "powered-by-a5",
              type: "Text",
              x: 0,
              y: 520,
              width: 360,
              height: 15,
              text: "Powered by AavanamKit",
              fontSize: 8,
              align: "center",
              fill: "#888888",
            },
          ],
        },
      ],
    },
  },
  {
    id: "pro-thermal-receipt",
    name: "Professional Receipt",
    description:
      "A clean, continuous-roll receipt for thermal printers with all necessary details.",
    preview: "https://placehold.co/300x500?text=Professional+Receipt",
    template: {
      dataSchema: {
        receiptNumber: "string",
        receiptDate: "string",
        items: [{ description: "string", price: "number" }],
      },
      pageSettings: {
        mode: "roll",
        width: 220,
        height: 600,
        marginTop: 20,
        marginRight: 10,
        marginBottom: 20,
        marginLeft: 10,
      },
      pages: [
        {
          id: "page-1",
          width: 220,
          height: 600,
          elements: [
            {
              id: "logo-th",
              type: "Image",
              x: 60,
              y: 0,
              width: 80,
              height: 40,
              src: "https://placehold.co/160x80/EFEFEF/31343C?text=Logo",
            },
            {
              id: "shop-name-th",
              type: "Text",
              x: 0,
              y: 50,
              width: 200,
              height: 15,
              text: "Mobile Repair Experts",
              fontSize: 12,
              fontStyle: "bold",
              align: "center",
            },
            {
              id: "shop-addr-th",
              type: "Text",
              x: 0,
              y: 65,
              width: 200,
              height: 30,
              text: "123 Tech Lane, Circuit City\nwww.mobilerepair.experts",
              fontSize: 9,
              align: "center",
            },
            {
              id: "receipt-num-th",
              type: "Text",
              x: 0,
              y: 105,
              width: 200,
              height: 12,
              text: "Receipt #: 12345",
              dataBinding: { property: "text", field: "receiptNumber" },
              fontSize: 9,
            },
            {
              id: "date-th",
              type: "Text",
              x: 0,
              y: 118,
              width: 200,
              height: 12,
              text: "Date: 08/06/2025",
              dataBinding: { property: "text", field: "receiptDate" },
              fontSize: 9,
            },
            {
              id: "line-th-1",
              type: "Shape",
              shape: "line",
              x: 0,
              y: 135,
              width: 200,
              height: 1,
              stroke: "#000000",
              strokeWidth: 1,
            },
            {
              id: "items-table-th",
              type: "Table",
              x: 0,
              y: 145,
              width: 200,
              height: 100,
              dataBinding: { property: "items", field: "items[]" },
              columns: [
                { header: "Item", dataKey: "description" },
                { header: "Price", dataKey: "price" },
              ],
            },
            {
              id: "thanks-th",
              type: "Text",
              x: 0,
              y: 280,
              width: 200,
              height: 15,
              text: "Thank you for your visit!",
              fontSize: 10,
              fontStyle: "bold",
              align: "center",
            },
            {
              id: "barcode-th",
              type: "Barcode",
              x: 25,
              y: 300,
              width: 150,
              height: 40,
              text: "1234567890",
            },
          ],
        },
      ],
    },
  },
  {
    id: "pro-repair-ticket",
    name: "Job Repair Ticket",
    description:
      "A compact ticket with essential customer and device information for tracking repairs.",
    preview: "https://placehold.co/350x250?text=Repair+Ticket",
    template: {
      dataSchema: {
        ticketNumber: "string",
        customer: { name: "string" },
        deviceModel: "string",
        reportedIssue: "string",
      },
      pageSettings: {
        mode: "paged",
        size: "custom",
        width: 320,
        height: 250,
        marginTop: 20,
        marginRight: 20,
        marginBottom: 20,
        marginLeft: 20,
      },
      pages: [
        {
          id: "page-1",
          width: 320,
          height: 250,
          elements: [
            {
              id: "ticket-title",
              type: "Text",
              x: 0 + 20,
              y: 0 + 20,
              width: 280,
              height: 20,
              text: "JOB REPAIR TICKET",
              fontSize: 16,
              fontStyle: "bold",
              align: "center",
            },
            {
              id: "ticket-shop",
              type: "Text",
              x: 0 + 20,
              y: 20 + 20,
              width: 280,
              height: 15,
              text: "Mobile Repair Experts",
              fontSize: 9,
              align: "center",
            },
            {
              id: "line-tk-1",
              type: "Shape",
              shape: "line",
              x: 0 + 20,
              y: 40 + 20,
              width: 280,
              height: 1,
              stroke: "#000000",
              strokeWidth: 1,
            },
            {
              id: "ticket-num-label",
              type: "Text",
              x: 0 + 20,
              y: 50 + 20,
              width: 280,
              height: 15,
              text: "REPAIR ID",
              fontSize: 10,
              align: "center",
            },
            {
              id: "ticket-num-val",
              type: "Text",
              x: 0 + 20,
              y: 65 + 20,
              width: 280,
              height: 30,
              text: "T-12345",
              dataBinding: { property: "text", field: "ticketNumber" },
              fontSize: 24,
              fontStyle: "bold",
              align: "center",
            },
            {
              id: "line-tk-2",
              type: "Shape",
              shape: "line",
              x: 0 + 20,
              y: 100 + 20,
              width: 280,
              height: 1,
              stroke: "#cccccc",
              strokeWidth: 1,
            },
            {
              id: "cust-label",
              type: "Text",
              x: 10 + 20,
              y: 110 + 20,
              width: 100,
              height: 15,
              text: "Customer:",
              fontSize: 10,
              fontStyle: "bold",
            },
            {
              id: "cust-val",
              type: "Text",
              x: 120 + 20,
              y: 110 + 20,
              width: 150,
              height: 15,
              dataBinding: { property: "text", field: "customer.name" },
              fontSize: 10,
            },
            {
              id: "device-label",
              type: "Text",
              x: 10 + 20,
              y: 130 + 20,
              width: 100,
              height: 15,
              text: "Device:",
              fontSize: 10,
              fontStyle: "bold",
            },
            {
              id: "device-val",
              type: "Text",
              x: 120 + 20,
              y: 130 + 20,
              width: 150,
              height: 15,
              dataBinding: { property: "text", field: "deviceModel" },
              fontSize: 10,
            },
            {
              id: "issue-label",
              type: "Text",
              x: 10 + 20,
              y: 150 + 20,
              width: 100,
              height: 15,
              text: "Reported Issue:",
              fontSize: 10,
              fontStyle: "bold",
            },
            {
              id: "issue-val",
              type: "Text",
              x: 120 + 20,
              y: 150 + 20,
              width: 150,
              height: 40,
              dataBinding: { property: "text", field: "reportedIssue" },
              fontSize: 10,
            },
            {
              id: "footer-tk",
              type: "Text",
              x: 0 + 20,
              y: 200 + 20,
              width: 280,
              height: 15,
              text: "Please present this ticket upon collection.",
              fontSize: 8,
              align: "center",
            },
          ],
        },
      ],
    },
  },
];

// This function simulates fetching the templates from an API
export const fetchTemplatesAPI = () => {
  return new Promise((resolve) => {
    // Simulate network delay
    setTimeout(() => {
      resolve(templates);
    }, 500);
  });
};
