# Name of our workflow - this will appear in the "Actions" tab on GitHub
name: AavanamKit Engine CI

# This section defines WHEN the workflow should run
on:
  # Run on every push to the 'develop' branch
  push:
    branches: [develop]
  # Run on every Pull Request that targets the 'develop' branch
  pull_request:
    branches: [develop]

# This section defines the actual jobs to be run
jobs:
  # We have one job called 'build-and-test'
  build-and-test:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # The sequence of steps to perform
    steps:
      # Step 1: Check out our repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the correct version of Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Use a recent Long-Term Support version
          cache: "npm" # Cache npm dependencies to speed up future runs

      # Step 3: Install all dependencies for our monorepo
      - name: Install Dependencies
        run: npm ci

      # Step 4: Run the tests specifically for our engine package
      - name: Run Engine Tests
        run: npm test --workspace=@aavanamkit/engine
